#!/bin/bash
d=$1
if [ "$d" = "" ]; then d=1; fi

while true
do
  sleep $d &
  s=$!
  outt=`date +"%D %T.%N" | sed "s/\(.*\.[0-9][0-9][0-9]\).*/\1/"`
  out0=`vcgencmd measure_temp`
  out1=`vcgencmd measure_clock arm`
  out2=`top -bn 1 -1 | grep "^%Cpu"`
  out3=`top -bn 1 | grep "^%Cpu"`
  out4=`top -bn 1 | grep "free"`
  wait $s
  echo -e '\x1bc\n'"$outt($d)  $out0  $out1\n\n$out2\n\n$out3\n\n$out4" &
done
